export const cards = [
  {
    id: '000',
    title: 'SOFA',
    img: '0.png',
    category: 'Design',
  },
  {
    id: '001',
    title: 'Keyboard',
    img: '1.png',
    category: 'Branding',
  },
  {
    id: '002',
    title: 'Work Media',
    img: '2.png',
    category: 'Illustration',
  },
  {
    id: '003',
    title: 'DDDone',
    img: '3.png',
    category: 'Motion',
  },
  {
    id: '004',
    title: 'Abstract',
    img: '4.png',
    category: 'Design',
  },
  {
    id: '005',
    title: 'HandP',
    img: '5.png',
    category: 'Branding',
  },
  {
    id: '006',
    title: 'Architect',
    img: '6.png',
    category: 'Motion',
  },
  {
    id: '007',
    title: 'CalC',
    img: '7.png',
    category: 'Design',
  },
  {
    id: '008',
    title: 'Sport',
    img: '8.png',
    category: 'Branding',
  },
  {
    id: '009',
    title: 'Title',
    img: '9.png',
    category: 'Design',
  },
  {
    id: '010',
    title: 'Architect',
    img: '10.png',
    category: 'Branding',
  },
  {
    id: '011',
    title: 'Sport',
    img: '11.png',
    category: 'Illustration',
  },
  {
    id: '012',
    title: 'Sport',
    img: '12.png',
    category: 'Branding',
  },
  {
    id: '013',
    title: 'Sport',
    img: '13.png',
    category: 'Illustration',
  },
  {
    id: '014',
    title: 'Architect',
    img: '14.png',
    category: 'Branding',
  },
  {
    id: '015',
    title: 'Abstract',
    img: '15.png',
    category: 'Illustration',
  },
  {
    id: '016',
    title: 'Sport',
    img: '16.png',
    category: 'Design',
  },
  {
    id: '017',
    title: 'Abstract',
    img: '17.png',
    category: 'Branding',
  },
  {
    id: '018',
    title: 'Sport',
    img: '18.png',
    category: 'Motion',
  },
  {
    id: '019',
    title: 'HandP',
    img: '19.png',
    category: 'Illustration',
  },
  {
    id: '020',
    title: 'Abstract',
    img: '20.png',
    category: 'Motion',
  },
  {
    id: '021',
    title: 'Sport',
    img: '21.png',
    category: 'Design',
  },
  {
    id: '022',
    title: 'HandP',
    img: '22.png',
    category: 'Motion',
  },
  {
    id: '023',
    title: 'Abstract',
    img: '23.png',
    category: 'Branding',
  },
  {
    id: '024',
    title: 'Sport',
    img: '24.png',
    category: 'Design',
  },
  {
    id: '025',
    title: 'Sport',
    img: '25.png',
    category: 'Motion',
  },
  {
    id: '026',
    title: 'HandP',
    img: '26.png',
    category: 'Branding',
  },
];

export const categories = ['Show all', 'Design', 'Branding', 'Illustration', 'Motion'];
